
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ./ha/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ:-America/Los_Angeles}
    ports:
      - "8123:8123"
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    depends_on:
      - mosquitto
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  agent:
    build: ./agent
    container_name: ha-agent
    environment:
      - HA_BASE_URL=${HA_BASE_URL:-http://homeassistant:8123}
      - HA_LONG_LIVED_TOKEN=${HA_LONG_LIVED_TOKEN:-changeme}
      - AGENT_TOKEN=${AGENT_TOKEN:-devtoken}
    ports:
      - "8091:8091"
    depends_on:
      - homeassistant
    restart: unless-stopped
