
homeassistant:
  name: Capstone Home
  unit_system: metric
  time_zone: America/Los_Angeles
  allowlist_external_dirs:
    - /config

# Basic onboarding helpers
default_config:

# Enable intents (HA's internal intent engine)
intent:

# Example: a simple intent for lights (extend as needed)
intent_script: !include intents.yaml

# MQTT defaults (optional)
mqtt:
  broker: mosquitto
  port: 1883

# Example helper entities you can create in the UI:
# - light.kitchen
# - switch.desk_lamp
# - scene.movie_time
