
# Add intent scripts if you want HA-native intents.
# Your project will primarily call the REST API via the agent service.
# This file is here as an example of HA's intent feature.
example_turn_on_light:
  speech:
    text: "Turning on the light."
  action:
    - service: light.turn_on
      target:
        entity_id: light.kitchen
